version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    build: ./app
    deploy:
      replicas: 3
    volumes:
      - ./logs:/logs

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - ./db/data:/var/lib/mysql
