version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app  # לא צריך שמות ספציפיים כמו app1, app2 וכו'

  app:
    build: ./app
    deploy:
      replicas: 10  # הגדלת מספר ה־replicas ל־10
    volumes:
      - ./logs:/logs
    environment:
      - FLASK_ENV=production

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - ./db/data:/var/lib/mysql
